
spring:
  data:
    mongodb:
      uri: mongodb+srv://martina10:corso10@cluster0.xltlu.mongodb.net/corso10
      port: 27017
      auto-index-creation: true
server:
  port: 8080







  

 
