spring: 
    datasource:
      mongodb: 
      uri: mongodb+srv://martina10:<corso10>@cluster0.xltlu.mongodb.net/corso10?retryWrites=true&w=majority
      username: martina10
      password: corso10
      
server:
   port: 27017







  

 
